services:
  db:
    image: paradedb/paradedb:0.24.1
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - rag_pg_data:/var/lib/postgresql

volumes:
  rag_pg_data:
